### PR TITLE
GH-166: Fix linting and formatting

### LINKED ISSUE #166: Fix linting and formatting
A configuration error was keeping ESLint/Prettier from running.

### PR DESCRIPTION
**Pull request by roblafeve**
## Description

Addresses various listing and formatting issues.

ab541fc GH-166: Update eslint config
fb850b4 GH-166: Run test:lint:fix on project
5e3d3c9 GH-166: Fix test:lint script and ignore consumers
df930dd GH-166: Remove bad eslint config
d479928 GH-166: Remove `.vscode`

closes #166 

## 🔎 Reviewer Checklist

> _Checked off by PR **Reviewers**_

- [ ] Merge destination is correct
- [ ] Code is correct as understood and conforms to quality standards

---

> ### Roles & Responsibilities
>
> #### 👨‍💻 Assignee
>
> - Initiator of this PR (be sure to set in GitHub UI)
> - Addresses feedback and change requests
> - Merges PR once approved (usually deletes branch unless `develop` or `release`)
>
> #### 👩‍💻 Reviewer
>
> - Invited to review PR by **Assignee** (via GitHub UI)
> - Is expected to complete a review and address followup

### CODE REVIEW

**Comment by blaketarter** [comment]
@roblafeve Is requiring return types something we want to mandate on all projects? Also would this mean that we have to specify the return type for React components?

**Comment by roblafeve** [comment]
> @roblafeve Is requiring return types something we want to mandate on all projects? Also would this mean that we have to specify the return type for React components?

@blaketarter I have been wondering this too. On one hand, return types actually help you while writing code vs. relying on the implicit contract based on what you happen to return. On the other, some folks may find this heavy-handed. I am happy to experiment with it in this codebase to see how it feels, so that's why I've changed it. So it's clear, this doesn't affect any consumer configuration.

What are your thoughts?

**Comment by blaketarter** [comment]
Since this is only for this codebase I'll go ahead and approve this PR, but the larger question of whether we should mandate it or not. I personally would like to have explicit return types, but I'm not sure if that's a default that we can have realistically.

**Review by blaketarter — APPROVED** [review]

**Comment by roblafeve** [comment]
@blaketarter yeah, I think we have some work to do before we can sensibly turn that on, but also, I think each team can decide. Might just be a practice we need to show the benefits of.

**Pull request merged**
